services:
  - type: web
    name: caesartalk-demo
    env: docker # <--- CAMBIO IMPORTANTE: Ahora usamos Docker
    plan: free
    branch: main
    envVars:
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite # Ruta interna de Docker
      - key: APP_KEY
        sync: false
